### ISSUE TITLE
dsniff requirements

### ISSUE THREAD

**Issue by Summer20130725** [GregHoff/dsniff#1]
1.dsniff compile time requirements: 
 - libpcap-dev
 - libnet-dev
 - libdb-dev 
 - libnids-dev
 - libssl-dev 
 ### Note: Please do not use the version of libssl1.0 otherwise an error will be reported during compilation
 - openssl 

### all requirenemts
```
apt-get install make gcc g++ gdb libpcap-dev libnet-dev libdb-dev libnids-dev libssl-dev openssl -y
```

**Comment by GregHoff** [comment]
Thanks for the suggestion.  I'll add the information to README.md
